### ISSUE TITLE
repo does not install cleanly

### ISSUE THREAD

**Issue by IanMulvany** [elifesciences/elife-metrics#1]
./install.sh
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in venv/bin/python2.7
Also creating executable in venv/bin/python
Installing setuptools, pip...done.
no settings.py found. quitting while I'm ahead.

I had to `sudo pip install -r requirements.txt` to get the repo to install.

**Comment by lsh-0** [comment]
this has been fixed in metrics and all django projects for a while now. closing.
